steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - '${_GCR_HOSTNAME}/${_PROJECT}/${_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA'
  - '.'
  - '-f'
  - 'src/app/Dockerfile'
  id: Build
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - '${_GCR_HOSTNAME}/${_PROJECT}/${_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA'
  id: Push
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '${_IMAGE_NAME}'
  - '--image'
  - '${_GCR_HOSTNAME}/${_PROJECT}/${_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA'
  - '--platform'
  - 'managed'
  - '--region'
  - 'us-central1'
  - '--port'
  - '8080'
  - '--allow-unauthenticated'
  id: Deploy

images:
- '${_GCR_HOSTNAME}/${_PROJECT}/${_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
